name: Node.js CI

on:
  push:
    branches: [ add-load-balancer, principal ]
  pull_request:
    branches: [ principal ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm install
    - name: Check Syntax
      run: node --check src/clima.mjs src/sistema.mjs

